# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccs" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "6ec2d6109ec62d318c96d2344e6e3c708564ba0b090e36180e41be250c47f4c7"
      url "https://github.com/RLSWE/ccs/releases/download/v#{version}/ccs_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "16a344f1e402778ba9bc86c6d5f7349e75a739dcef6ae756de3013086e4c7f1f"
      url "https://github.com/RLSWE/ccs/releases/download/v#{version}/ccs_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f4ef996e881155a760ac9c959c87699ac7262a91044199d49979da6b8a4c2066"
      url "https://github.com/RLSWE/ccs/releases/download/v#{version}/ccs_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7bba5f6b2af8e2b5b103e116eb1029a71b4e8f5af3b0250d1e67491b3cab7ad7"
      url "https://github.com/RLSWE/ccs/releases/download/v#{version}/ccs_linux_arm64.tar.gz"
    end
  end

  name "ccs"
  desc "Fast fuzzy finder for Claude Code sessions"
  homepage "https://github.com/RLSWE/ccs"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccs"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ccs"]
    end
  end

  # No zap stanza required

end
