# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccs" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "722c8ed185a4af3cb9ce794b20880540bcee1887422f41db00c7605e73903fc1"
      url "https://github.com/RLSWE/ccs/releases/download/v#{version}/ccs_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e85f75a4617a13b1f485f81433f55f72c7b0b55f6e18d05f2da0b3ddd3824c64"
      url "https://github.com/RLSWE/ccs/releases/download/v#{version}/ccs_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e608cc968c844af764e62a81fc63af8109ed135e92d006e89b8ce304968f2dcd"
      url "https://github.com/RLSWE/ccs/releases/download/v#{version}/ccs_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5f7be7fe904ae58b01f3f2afc298ec2fda1112e05e95345d13203caa74f98dcd"
      url "https://github.com/RLSWE/ccs/releases/download/v#{version}/ccs_linux_arm64.tar.gz"
    end
  end

  name "ccs"
  desc "Fast fuzzy finder for Claude Code sessions"
  homepage "https://github.com/RLSWE/ccs"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccs"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ccs"]
    end
  end

  # No zap stanza required

end
