# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccs" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "61b9f18a4f2e9746f2938cfa52a1fbcd3d5846be1db3911877f17ef37d30c48e"
      url "https://github.com/RLSWE/ccs/releases/download/v#{version}/ccs_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "351bd64bd1db8ea9c045b2e237c8470b6bc5026bd7719849cc65b13de985f806"
      url "https://github.com/RLSWE/ccs/releases/download/v#{version}/ccs_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "35550ed7f3b6ba62a4f4574886f80f2b9d444c5669b55bb5e5466d17b7259b86"
      url "https://github.com/RLSWE/ccs/releases/download/v#{version}/ccs_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "035bd96e79286ba8e2071c733c07285f484effc026118cafebcf151bf335d7e7"
      url "https://github.com/RLSWE/ccs/releases/download/v#{version}/ccs_linux_arm64.tar.gz"
    end
  end

  name "ccs"
  desc "Fast fuzzy finder for Claude Code sessions"
  homepage "https://github.com/RLSWE/ccs"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccs"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ccs"]
    end
  end

  # No zap stanza required

end
